### ISSUE TITLE
Should not list redhat support

### ISSUE THREAD

**Issue by mostlegitdotcom** [zenoamaro/ansible-varnish#1]
Here's what happens when tested against a redhat server: 
fatal: [vps16932.inmotionhosting.com] => failed to parse: {"msg": "[Errno 2] No such file or directory", "failed": true, "cmd": ["apt-get", "update", "&&", "apt-get", "install", "python-apt", "-y", "-q"], "rc": 2}
{"msg": "Could not import python modules: apt, apt_pkg. Please install python-apt package.", "failed": true}

Of course apt-get isn't installed. red hat is yum based.

**Comment by zenoamaro** [comment]
Thanks, you are right. 

Although support was not present in the metafile, it makes sense not to mention untested/unsupported platforms at all. It's not listed anymore as 16572bbaa0.

If you are using RedHat, any chance you can contribute and test some support for it?
